services:
  - docker
before_install:
  - docker pull nimlang/nim:0.18.0
script:
  - docker run --rm -v `pwd`:/usr/src/app -w /usr/src/app nimlang/nim /bin/bash -c "nimble install -y; nimble test"
notifications:
  email:
    on_failure: never
    on_success: never
